name: Docs to Wiki on merge
# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - .wiki/** # This includes all sub folders
    branches:
      - main
permissions:
  contents: write
env:
  WIKI_DIR: .wiki
  TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is the repository secret
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name
jobs:
  docs_to_wiki:
    name: Docs to Wiki on merge
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content
      - name: Clone wiki 
        run: |
          git clone https://$OWNER:$TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git tmp_wiki
      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content
      - name: Sync and push changes to wiki
        run: |
          rsync -av --delete $WIKI_DIR/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "${{ github.event.head_commit.message }}" --author="${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.author.email }}"
          git push origin master
